import type { Metadata } from "next";
import Navbar from "@/app/components/Navbar";
import Footer from "@/app/components/Footer";
import "./global.css";
import Providers from "./providers";
import { Divider } from "@heroui/react";
import React from "react";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className="h-full">
      <body className="flex flex-col min-h-screen">
        <Providers>
          <Navbar />
          <Divider className="my-4" />
          <main className="flex-grow container mx-auto px-6">{children}</main>
          <Divider className="my-4" />
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
